###GET DATA
GET https://api.binance.com/api/v3/exchangeInfo

###GET DATA
GET https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC

###GET DATA
GET https://api.binance.com/api/v3/exchangeInfo?symbol=BNBBTC